let obj = [
  [
    {
      CATEGORY: [
        { name: "All Shoes", url: "" },
        { name: "Sneakers", url: "" },
        { name: "Boots", url: "" },
        { name: "High tops", url: "" },
        { name: "Low top", url: "" },
        { name: "Slides", url: "" },
        { name: "Slip-ons", url: "" },
        { name: "Sustainable sneakers", url: "" },
        { name: "Sandals", url: "" },
      ],
    },
    {
      SEASON: [
        { name: "Spring", url: "" },
        { name: "Summer", url: "" },
        { name: "Autumn", url: "" },
        { name: "Winter", url: "" },
      ],
      SPORT: [
        { name: "Running", url: "" },
        { name: "Skate", url: "" },
        { name: "Basket", url: "" },
        { name: "Fitness", url: "" },
        { name: "Outdoor", url: "" },
      ],
    },
    {
      "POPULAR MODELS": [
        { name: "adidas Samba", url: "" },
        { name: "adidas Gazelle", url: "" },
        { name: "Nike Air Max", url: "" },
        { name: "Nike Dunk", url: "" },
        { name: "Nike Air Force 1", url: "" },
        { name: "Vans KNU SKOOL", url: "" },
        { name: "Hoka One One Clifton 8", url: "" },
        { name: "New Balance XC-72", url: "" },
        { name: "Asics Gel-Kayano 14", url: "" },
        { name: "On Cloud", url: "" },
        { name: "adidas campus 00s", url: "" },
        { name: "Converse Chuck Taylor 70s", url: "" },
        { name: "Converse Run Star Hike", url: "" },
      ],
    },
    {
      "FAVOURITE BRANDS": [
        { name: "Nike", url: "" },
        { name: "adidas Originals", url: "" },
        { name: "adidas Performance", url: "" },
        { name: "New Balance", url: "" },
        { name: "Y-3", url: "" },
        { name: "Converse", url: "" },
        { name: "Reebok", url: "" },
        { name: "HOKA ONE ONE", url: "" },
        { name: "Vans Vault", url: "" },
        { name: "Vans", url: "" },
        { name: "Asics", url: "" },
        { name: "Puma", url: "" },
        { name: "Salomon Advanced", url: "" },
        { name: "On", url: "" },
      ],
    },
  ],
  [
    {
      "FAVOURITE BRANDS": [
        { name: "All brands", url: "" },
        { name: "A Bathing Ape", url: "" },
        { name: "A-COLD-WALL", url: "" },
        { name: "a.p.c.", url: "" },
        { name: "adidas Originals", url: "" },
        { name: "adidas Performance", url: "" },
        { name: "Asics", url: "" },
        { name: "Ambush", url: "" },
        { name: "Awake NY", url: "" },
        { name: "Birkenstock", url: "" },
        { name: "C.P. Company", url: "" },
        { name: "Calvin Klein", url: "" },
        { name: "Carhartt WIP", url: "" },
        { name: "Casio", url: "" },
        { name: "Columbia", url: "" },
      ],
    },
    {
      "\u200e": [
        { name: "Comme des Garçons SHIRT", url: "" },
        { name: "Converse", url: "" },
        { name: "CREP Protect", url: "" },
        { name: "Daily Paper", url: "" },
        { name: "Dickies", url: "" },
        { name: "Diesel", url: "" },
        { name: "Dr. Martens", url: "" },
        { name: "Filling Pieces", url: "" },
        { name: "Fjällräven", url: "" },
        { name: "Fred Perry", url: "" },
        { name: "Heliot Emil", url: "" },
        { name: "HERON PRESTON", url: "" },
        { name: "Herschel Supply Co", url: "" },
        { name: "HOKA", url: "" },
        { name: "Jordan", url: "" },
      ],
    },
    {
      "\u200e": [
        { name: "KAHRU", url: "" },
        { name: "LEGO", url: "" },
        { name: "Levi's", url: "" },
        { name: "MARKET", url: "" },
        { name: "Medicon Toy", url: "" },
        { name: "Mizuno", url: "" },
        { name: "Moon Boot", url: "" },
        { name: "New Balance", url: "" },
        { name: "New Era", url: "" },
        { name: "Nike", url: "" },
        { name: "On", url: "" },
        { name: "Patta", url: "" },
        { name: "PLEASURES", url: "" },
        { name: "Poutnik by Tilak", url: "" },
        { name: "Puma", url: "" },
      ],
    },
    {
      "\u200e": [
        { name: "RAF SIMMONS", url: "" },
        { name: "Saucony", url: "" },
        { name: "Reebok", url: "" },
        { name: "Timberland", url: "" },
        { name: "Rick Owens DRKSHDW", url: "" },
        { name: "Salomon Advanced", url: "" },
        { name: "UGG", url: "" },
        { name: "Stüssy", url: "" },
        { name: "The North Face", url: "" },
        { name: "Tommy Hilfiger", url: "" },
        { name: "Under Armour", url: "" },
        { name: "Vans", url: "" },
        { name: "Veja", url: "" },
        { name: "Y-3", url: "" },
      ],
    },
  ],
  [
    {
      "DISCOUNTS BY AMOUNT": [
        { name: "Sales from 20%", url: "" },
        { name: "Sales from 40%", url: "" },
        { name: "Sales from 60%", url: "" },
      ],
    },
    {
      "DISCOUNTS BY BRAND": [
        { name: "Nike", url: "" },
        { name: "Adidas Originals", url: "" },
        { name: "New Balance", url: "" },
        { name: "Converse", url: "" },
        { name: "Vans", url: "" },
      ],
    },
  ],
];

export default obj;
